# 本地开发环境配置
# 用于本地开发和测试，包含更多默认配置
server:
  port: 8888

spring:
  application:
    name: admin-service

  # 配置导入 - 从Nacos加载配置（可选）
  config:
    import: optional:nacos:admin-service.yml

  # 本地开发默认安全配置
  security:
    user:
      name: admin
      password: admin123

  boot:
    admin:
      ui:
        title: HavenButler Admin Console
        brand: HavenButler管理控制台

  # Nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        enabled: true
        service: ${spring.application.name}
        metadata:
          management.context-path: /actuator
          version: 1.0.0
          zone: admin
          environment: ${ENVIRONMENT:local}
      config:
        server-addr: ${NACOS_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        file-extension: yml
        enabled: true
        shared-configs:
          - data-id: havenbutler-common.yml
            group: DEFAULT_GROUP
            refresh: true

  # Redis配置 (common模块需要)
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: ${REDIS_DATABASE:0}
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

# base-model 统一配置 (按照最新规范)
base-model:
  # 链路追踪配置
  trace:
    enabled: true
    prefix: "tr"
    exclude-paths:
      - "/actuator/**"
      - "/swagger-ui/**"
      - "/admin/**"
      - "/health"
      - "/favicon.ico"
    include-request-params: false      # Admin服务不记录请求参数
    include-response-body: false       # 不记录响应体

  # 统一响应配置
  response:
    include-trace-id: true
    include-timestamp: true
    include-server-info: false
    success-message: "操作成功"

  # 全局异常处理
  exception:
    enabled: true
    include-stack-trace: false         # 生产环境不暴露堆栈
    include-error-detail: true
    default-error-message: "系统繁忙，请稍后重试"

  # 缓存配置
  cache:
    enabled: true
    key-prefix: "haven:admin:"
    default-ttl: 300                   # 5分钟缓存

  # 分布式锁配置
  distributed-lock:
    enabled: true
    default-timeout: 30
    auto-renew: true

  # 安全配置
  security:
    jwt-secret: "${JWT_SECRET:}"       # 必须通过环境变量注入
    jwt-expiration: 86400000           # 24小时
    jwt-clock-skew: 30                 # 30秒时钟偏差容忍

  # 指标收集
  metrics:
    enabled: true
    export-interval: 60

  # 消息队列 (Admin服务一般不需要)
  messaging:
    enabled: false
    default-timeout: 5000
    max-retry: 3

  # 日志配置
  log:
    enabled: true
    level: INFO
    format: JSON
    include-headers: false
    include-payload: false             # Admin服务不记录载荷
    max-payload-size: 1024

  # 限流配置
  rate-limit:
    enabled: true
    default-limit: 100                 # Admin操作相对保守
    default-window: 60
    redis-key-prefix: "admin_rate_limit:"


# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Prometheus配置
prometheus:
  url: ${PROMETHEUS_URL:http://localhost:9090}

# 告警配置
alert:
  notification:
    webhook:
      url: ${ALERT_WEBHOOK_URL:}
    email:
      enabled: ${ALERT_EMAIL_ENABLED:false}
    sms:
      enabled: ${ALERT_SMS_ENABLED:false}

# 日志配置
logging:
  level:
    com.haven: DEBUG
    de.codecentric.boot.admin: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [%X{traceId:-}] - %msg%n"
  file:
    name: ${LOGGING_FILE_PATH:/app/logs}/admin-service.log
    max-size: 100MB
    max-history: 30
    total-size-cap: 3GB