# Docker环境配置 - 本地最小化配置，主要配置从Nacos加载
server:
  port: 8081

spring:
  application:
    name: storage-service

  config:
    import: optional:nacos:storage-service.yml

  # Nacos配置 - Docker环境
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:nacos-admin:8848}
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        enabled: true
        service: ${spring.application.name}
        metadata:
          management.context-path: /actuator
          version: 1.0.0
          zone: storage
          environment: ${ENVIRONMENT:docker}
      config:
        server-addr: ${NACOS_ADDR:nacos-admin:8848}
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        file-extension: yml
        enabled: true
        shared-configs:
          - data-id: havenbutler-common.yml
            group: DEFAULT_GROUP
            refresh: true
        extension-configs:
          - data-id: storage-service-docker.yml
            group: DEFAULT_GROUP
            refresh: true