version: '3.8'

services:
  # Nacos配置中心和服务发现
  nacos:
    image: nacos/nacos-server:v2.3.2-slim
    container_name: nacos-admin
    environment:
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
      - SPRING_DATASOURCE_PLATFORM=derby
      - NACOS_SERVER_PORT=8848
      # 显式禁用MySQL相关配置
      - MYSQL_SERVICE_HOST=
      - MYSQL_SERVICE_DB_NAME=
      - MYSQL_SERVICE_PORT=
      - MYSQL_SERVICE_USER=
      - MYSQL_SERVICE_PASSWORD=
    ports:
      - "8848:8848"
      - "9848:9848"
    networks:
      - haven-network
    volumes:
      - nacos-data:/home/nacos/data
      - nacos-logs:/home/nacos/logs
    restart: unless-stopped

  # Prometheus监控 - 使用轻量级版本
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus-admin
    ports:
      - "9090:9090"
    networks:
      - haven-network
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped

  # Admin管理服务
  admin-service:
    image: smart-home/admin-service:v1.0.0
    container_name: haven-admin-service
    ports:
      - "8888:8888"
    networks:
      - haven-network
    environment:
      # Spring Boot配置
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_APPLICATION_NAME=admin-service
      - SERVER_PORT=8888

      # Nacos配置
      - NACOS_ADDR=nacos:8848
      - NACOS_NAMESPACE=${NACOS_NAMESPACE:-public}
      - NACOS_GROUP=${NACOS_GROUP:-DEFAULT_GROUP}

      # 环境配置
      - ENVIRONMENT=${ENVIRONMENT:-dev}

      # 安全配置
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=admin123
      - SPRING_SECURITY_USER_ROLES=ADMIN

      # 监控配置
      - PROMETHEUS_URL=http://prometheus:9090
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always

      # 告警配置
      - ALERT_EMAIL_ENABLED=false
      - ALERT_SMS_ENABLED=false
      - ALERT_WEBHOOK_URL=

      # 日志配置
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_COM_HAVEN=DEBUG
      - TZ=Asia/Shanghai
    volumes:
      - admin-logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    depends_on:
      - nacos
    labels:
      - "com.haven.service=admin"
      - "com.haven.version=1.0.0"
      - "com.haven.description=HavenButler管理服务"

volumes:
  admin-logs:
    driver: local
  nacos-data:
    driver: local
  nacos-logs:
    driver: local
  prometheus-data:
    driver: local

networks:
  haven-network:
    external: true