# Docker环境配置 - 本地最小化配置，主要配置从Nacos加载
server:
  port: 8888

spring:
  application:
    name: admin-service

  config:
    import: optional:nacos:admin-service.yml

  # Nacos配置 - Docker环境
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:nacos:8848}
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        enabled: true
        service: ${spring.application.name}
        metadata:
          management.context-path: /actuator
          version: 1.0.0
          zone: admin
          environment: ${ENVIRONMENT:dev}
      config:
        server-addr: ${NACOS_ADDR:nacos:8848}
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        file-extension: yml
        enabled: true
        shared-configs:
          - data-id: havenbutler-common.yml
            group: DEFAULT_GROUP
            refresh: true
        extension-configs:
          - data-id: admin-service-docker.yml
            group: DEFAULT_GROUP
            refresh: true