# Docker环境配置 - 精简版
# 最小化本地配置，所有业务配置从Nacos加载
# 使用方式: java -jar admin-service.jar --spring.profiles.active=docker
server:
  port: 8888

spring:
  application:
    name: admin-service

  # 从Nacos加载完整配置
  config:
    import: nacos:admin-service.yml

  # Nacos配置 - Docker环境
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:nacos:8848}
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        enabled: true
      config:
        server-addr: ${NACOS_ADDR:nacos:8848}
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        file-extension: yml
        enabled: true
        shared-configs:
          - data-id: havenbutler-common.yml
            group: DEFAULT_GROUP
            refresh: true
        extension-configs:
          - data-id: admin-service-${ENVIRONMENT:docker}.yml
            group: DEFAULT_GROUP
            refresh: true

# 最小化管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always