# 本地开发环境专用配置
# 使用方式: mvn spring-boot:run -Dspring-boot.run.profiles=local

# 日志配置 - 本地开发环境
logging:
  file:
    name: logs/admin-service.log  # 本地开发使用相对路径

# base-model 配置 - 本地环境特定调整
base-model:
  # 链路追踪配置 - 本地环境详细日志
  trace:
    include-request-params: true   # 本地环境记录请求参数便于调试
    include-response-body: true    # 本地环境记录响应体便于调试

  # 异常处理 - 本地环境显示详细错误
  exception:
    include-stack-trace: true      # 本地环境显示堆栈追踪
    include-error-detail: true

  # 缓存配置 - 本地环境较短缓存便于调试
  cache:
    default-ttl: 60              # 本地环境1分钟缓存

# 日志级别 - 本地环境更详细的日志
logging:
  level:
    com.haven: DEBUG
    de.codecentric.boot.admin: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

# 管理端点 - 本地开发环境可以暴露更多端点
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,configprops,beans,loggers
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true  # 本地环境允许动态调整日志级别