server:
  port: 8888

spring:
  application:
    name: admin-service
  security:
    user:
      name: admin
      password: admin123

  boot:
    admin:
      ui:
        title: HavenButler Admin Console
        brand: HavenButler管理控制台

  # Nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:havenbutler}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        enabled: true
        service: ${spring.application.name}
        metadata:
          management.context-path: /actuator
          version: 1.0.0
          zone: admin
      config:
        server-addr: ${NACOS_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:havenbutler}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        file-extension: yaml
        enabled: true

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Prometheus配置
prometheus:
  url: ${PROMETHEUS_URL:http://localhost:9090}

# 告警配置
alert:
  notification:
    webhook:
      url: ${ALERT_WEBHOOK_URL:}
    email:
      enabled: ${ALERT_EMAIL_ENABLED:false}
    sms:
      enabled: ${ALERT_SMS_ENABLED:false}

# 日志配置
logging:
  level:
    com.haven: DEBUG
    de.codecentric.boot.admin: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"